const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { PrismaClient } = require('@prisma/client');
const { FinanceControlService } = require('../dist/src/finances/finance-control.service');
const { FinancesService } = require('../dist/src/finances/finances.service');
const { StudentsService } = require('../dist/src/students/students.service');
(async () => {
  if (!process.env.DATABASE_URL?.includes('_test')) throw Error('Isolated test database required');
  const db = new PrismaClient(), deliveries=[], control = new FinanceControlService(db, {send:async(...args)=>{deliveries.push(args);}}), finances = new FinancesService(db), students = new StudentsService(db, {});
  const actor = { userId: 'qa', username: 'QA', roles: ['ADMIN'] }, tag = randomUUID(), ids = [], batchIds = [];
  const day = '2000-01-15';
  try {
    assert.equal(await db.cashClosing.count({where:{day}}), 0, 'Test day must be unused');
    const input = { firstName: 'QA '+tag, lastName: 'Duplication', gender: 'MALE', dateOfBirth: '2020-01-01', generateInvoice: false, parentData: {firstName:'QA '+tag,lastName:'Parent',phone:'780001234',email:'qa@example.invalid'} };
    const a = await students.create(input, actor); ids.push(a.id);
    await assert.rejects(students.create(input, actor), e=>e.getStatus()===409 && e.getResponse().duplicates[0].id===a.id);
    assert.equal(await db.student.count({where:{firstName:input.firstName}}),1);
    const b = await students.create({...input, duplicateOverrideReason:'Deux enfants homonymes vérifiés'},actor); ids.push(b.id);
    assert.equal(await db.businessAudit.count({where:{entityId:b.id, action:'STUDENT_DUPLICATE_OVERRIDE'}}),1);
    const invoice = await finances.createInvoice({studentId:a.id,title:tag,type:'OTHER',amount:1000,dueDate:new Date()},actor);
    await finances.recordPayment({invoiceId:invoice.id,amount:400,paymentMethod:'CASH',paymentDate:day},actor);
    await control.saveInstallments(invoice.id,[{dueDate:'2030-01-01',amount:300},{dueDate:'2030-02-01',amount:300}],actor);
    await assert.rejects(control.saveInstallments(invoice.id,[{dueDate:'2030-01-01',amount:700}],actor));
    const approval=(await control.reminderPreview(invoice.id)).approvalToken;
    await assert.rejects(control.sendReminder(invoice.id,true,actor,'obsolete-preview'));
    await control.sendReminder(invoice.id,true,actor,approval);
    await assert.rejects(control.sendReminder(invoice.id,true,actor,approval));
    assert.equal(deliveries.length,1,'Only one email per invoice/day');
    assert.equal((await control.installments(invoice.id)).length,2);
    let saved = await db.invoice.findUniqueOrThrow({where:{id:invoice.id},include:{payments:true}});
    await assert.rejects(control.cancelInvoice(invoice.id,'Facture de test annulée',actor));
    await Promise.all([control.cancelPayment(saved.payments[0].id,'Paiement enregistré par erreur',actor),control.cancelPayment(saved.payments[0].id,'Paiement enregistré par erreur',actor)]);
    saved=await db.invoice.findUniqueOrThrow({where:{id:invoice.id}}); assert.equal(saved.paidAmount,0);assert.equal(saved.balance,1000);
    await control.cancelInvoice(invoice.id,'Facture de test annulée',actor);
    assert.equal(await db.invoice.count({where:{id:invoice.id}}),1,'Cancellation keeps original invoice');
    await assert.rejects(finances.recordPayment({invoiceId:invoice.id,amount:100,paymentMethod:'CASH'},actor));
    const bulkA = await finances.createInvoice({studentId:a.id,title:tag,type:'OTHER',amount:1200,dueDate:new Date()},actor);
    const bulkB = await finances.createInvoice({studentId:a.id,title:tag,type:'OTHER',amount:800,dueDate:new Date()},actor);
    await finances.recordPayment({invoiceId:bulkA.id,amount:200,paymentMethod:'WAVE',paymentDate:day},actor);
    const batchInput={invoices:[{id:bulkA.id,balance:1000},{id:bulkB.id,balance:800}],paymentMethod:'WAVE'};
    await assert.rejects(finances.settleBatch({...batchInput,invoices:[batchInput.invoices[0],batchInput.invoices[0]]},actor));
    const staleItems=[...batchInput.invoices].sort((a,b)=>a.id.localeCompare(b.id));
    staleItems[1]={...staleItems[1],balance:staleItems[1].balance-100};
    const paymentCountBefore=await db.payment.count({where:{invoiceId:{in:[bulkA.id,bulkB.id]}}});
    await assert.rejects(finances.settleBatch({...batchInput,invoices:staleItems},actor));
    assert.equal(await db.payment.count({where:{invoiceId:{in:[bulkA.id,bulkB.id]}}}),paymentCountBefore,'Rollback removes payments created before stale invoice');
    assert.equal((await db.invoice.findUniqueOrThrow({where:{id:bulkA.id}})).balance,1000,'Failed lot rolls back every invoice');
    const attempts=await Promise.allSettled([finances.settleBatch(batchInput,actor),finances.settleBatch(batchInput,actor)]);
    assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1,'Concurrent submission creates only one lot');
    const batch=attempts.find(x=>x.status==='fulfilled').value; batchIds.push(batch.batchId);
    assert.equal(batch.total,1800); assert.equal(batch.count,2);
    assert.equal(new Set(batch.payments.map(x=>x.paymentNumber)).size,2);
    assert.equal(await db.businessAudit.count({where:{entityId:batch.batchId,actorId:'qa',action:'PAYMENT_BATCH_SETTLED'}}),1);
    for(const id of [bulkA.id,bulkB.id]) {
      const paid=await db.invoice.findUniqueOrThrow({where:{id},include:{payments:true}});
      assert.equal(paid.balance,0); assert.equal(paid.paidAmount,paid.amount); assert.equal(paid.status,'PAID');
      assert.equal(paid.payments.at(-1).receivedById,'qa');
    }
    await assert.rejects(finances.settleBatch({...batchInput,invoices:[{id:invoice.id,balance:1000}]},actor));
    const correctionInvoice=await finances.createInvoice({studentId:a.id,title:tag,type:'OTHER',amount:50000,dueDate:new Date()},actor);
    const originalReceipt=(await finances.recordPayment({invoiceId:correctionInvoice.id,amount:50000,paymentMethod:'WAVE',paymentDate:day,reference:'TEST-CORRECTION'},actor)).createdPayment;
    const correctionData={amount:40000,expectedAmount:50000,expectedPaidAmount:50000,reason:'Erreur de saisie : seulement 40000 reçus'};
    await assert.rejects(control.correctPayment(originalReceipt.id,correctionData,{...actor,roles:['COMPTABLE']}),e=>e.getStatus()===403);
    await assert.rejects(control.correctPayment(originalReceipt.id,correctionData,{...actor,roles:['DIRECTEUR']}),e=>e.getStatus()===403);
    await assert.rejects(control.correctPayment(originalReceipt.id,{...correctionData,amount:60000},actor));
    await assert.rejects(control.correctPayment(originalReceipt.id,{...correctionData,reason:'Court'},actor));
    const correctionAttempts=await Promise.allSettled([control.correctPayment(originalReceipt.id,correctionData,actor),control.correctPayment(originalReceipt.id,correctionData,actor)]);
    assert.equal(correctionAttempts.filter(x=>x.status==='fulfilled').length,1);
    const corrected=correctionAttempts.find(x=>x.status==='fulfilled').value;
    assert.equal(corrected.paidAmount,40000); assert.equal(corrected.balance,10000); assert.equal(corrected.status,'PARTIAL');
    assert.equal(corrected.payments.length,2); assert.ok(corrected.payments.find(p=>p.id===originalReceipt.id).cancelledAt);
    assert.equal(corrected.createdPayment.paymentDate.toISOString(),originalReceipt.paymentDate.toISOString());
    assert.equal(corrected.createdPayment.reference,'TEST-CORRECTION'); assert.equal(corrected.createdPayment.receivedById,'qa');
    const audit=(await control.correctionHistory(correctionInvoice.id))[0];
    assert.equal(audit.actorId,'qa'); assert.equal(JSON.parse(audit.details).correctedAmount,40000);
    assert.equal((await control.preview(day)).byMethod.WAVE,40200,'Cancelled original is excluded from cash totals');
    const second = await finances.createInvoice({studentId:a.id,title:tag,type:'OTHER',amount:1000,dueDate:new Date()},actor);
    const result=await finances.recordPayment({invoiceId:second.id,amount:600,paymentMethod:'CASH',paymentDate:day},actor);
    assert.equal((await control.preview(day)).expectedCash,600);
    await assert.rejects(control.close({day,countedCash:590},actor));
    await control.close({day,countedCash:590,notes:'Écart de caisse vérifié'},actor);
    await assert.rejects(finances.recordPayment({invoiceId:second.id,amount:100,paymentMethod:'CASH',paymentDate:day},actor));
    await assert.rejects(control.cancelPayment(result.createdPayment.id,'Correction après clôture',actor));
    await assert.rejects(control.correctPayment(corrected.createdPayment.id,{amount:30000,expectedAmount:40000,expectedPaidAmount:40000,reason:'Correction après clôture interdite'},actor));
    assert.equal((await db.invoice.findUniqueOrThrow({where:{id:correctionInvoice.id}})).paidAmount,40000);
    const today=new Date().toISOString().slice(0,10);
    await db.cashClosing.create({data:{day:today,expectedCash:0,countedCash:0,difference:0,summary:'{}',actorId:'qa',actorName:'QA',actorRole:'ADMIN'}});
    try { await assert.rejects(finances.settleBatch({invoices:[{id:second.id,balance:400}],paymentMethod:'CASH'},actor)); }
    finally { await db.cashClosing.delete({where:{day:today}}); }
    console.log('PASS: duplicate rollback, audited homonym override, concurrent cancellation idempotency, payment preservation, closed-day locks');
  } finally {
    const invoices=await db.invoice.findMany({where:{studentId:{in:ids}},select:{id:true}});
    const invIds=invoices.map(x=>x.id);
    const pay=await db.payment.findMany({where:{invoiceId:{in:invIds}},select:{id:true}});
    const closing=await db.cashClosing.findUnique({where:{day}});
    await db.businessAudit.deleteMany({where:{entityId:{in:[...batchIds,...ids,...invIds,...pay.map(x=>x.id),...(closing?[closing.id]:[])]}}});
    await db.cashClosing.deleteMany({where:{day}});
    await db.paymentInstallment.deleteMany({where:{invoiceId:{in:invIds}}});
    await db.paymentReminder.deleteMany({where:{invoiceId:{in:invIds}}});
    await db.payment.deleteMany({where:{invoiceId:{in:invIds}}}); await db.invoice.deleteMany({where:{id:{in:invIds}}});
    await db.student.deleteMany({where:{id:{in:ids}}}); await db.parent.deleteMany({where:{firstName:'QA '+tag}});await db.$disconnect();
  }
})().catch(e=>{console.error(e);process.exit(1)});
