import { useEffect, useState } from 'react';
import api, { classesApi } from '../services/api';
export function AcademicTransitionPage() {
  const [years,setYears]=useState<any[]>([]),[yearId,setYearId]=useState(''),[preview,setPreview]=useState<any>(null),[assignments,setAssignments]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');
  const load=()=>classesApi.getAcademicYears().then(setYears);
  useEffect(()=>{void load().catch(()=>setError('Chargement impossible.'));},[]);
  useEffect(()=>{setPreview(null);setAssignments({});if(yearId) api.get(`/academic-transition/${yearId}`).then(r=>setPreview(r.data)).catch(e=>setError(e.response?.data?.message||'Chargement impossible.'));},[yearId]);
  const act=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();await load();if(yearId)setPreview((await api.get(`/academic-transition/${yearId}`)).data);}catch(e:any){setError(e.response?.data?.message||'Action impossible.');}finally{setBusy(false);}};
  return <div className="space-y-6 p-4 sm:p-6"><h1 className="text-2xl font-bold">Passage d’année scolaire</h1><p>Préparez l’année et les classes, choisissez les réinscriptions puis activez l’année. Les anciens dossiers sont conservés. Aucune facture n’est générée automatiquement.</p>{error&&<p role="alert" className="bg-red-50 p-3 text-red-700">{error}</p>}
  <form className="flex flex-wrap gap-3 rounded-xl border bg-white p-5" onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await api.post('/academic-transition',{name,startDate:start,endDate:end});setYearId(r.data.id);});}}><input aria-label="Nom de l’année" required pattern="[0-9]{4}-[0-9]{4}" placeholder="2027-2028" value={name} onChange={e=>setName(e.target.value)} className="rounded border p-2"/><label>Début <input required type="date" value={start} onChange={e=>setStart(e.target.value)} className="rounded border p-2"/></label><label>Fin <input required type="date" value={end} onChange={e=>setEnd(e.target.value)} className="rounded border p-2"/></label><button disabled={busy} className="rounded bg-emerald-600 px-4 py-2 text-white">Préparer et copier les classes</button></form>
  <label>Année cible <select value={yearId} onChange={e=>setYearId(e.target.value)} className="rounded border p-2"><option value="">Choisir une année</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.isCurrent?' — active':''}</option>)}</select></label>
  {preview&&!preview.year.isCurrent&&<section className="space-y-3 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Réinscriptions</h2><p>{preview.enrollments.length} élève(s) déjà réinscrit(s). Ne sélectionnez que les changements souhaités.</p>{preview.students.map((student:any)=><div key={student.id} className="flex flex-wrap justify-between gap-3 border-b py-2"><span>{student.firstName} {student.lastName} — {student.matricule} — {student.enrollments?.[0]?.classroom?.name}</span><select aria-label={`Classe pour ${student.matricule}`} value={assignments[student.id]||''} onChange={e=>setAssignments({...assignments,[student.id]:e.target.value})} className="rounded border p-2"><option value="">Ne pas modifier</option>{preview.year.classrooms.map((room:any)=><option key={room.id} value={room.id}>{room.name}</option>)}</select></div>)}<button disabled={busy||!Object.values(assignments).some(Boolean)} onClick={()=>void act(()=>api.post(`/academic-transition/${yearId}/enroll`,{enrollments:Object.entries(assignments).filter(([,id])=>id).map(([studentId,classroomId])=>({studentId,classroomId}))}))} className="rounded bg-emerald-600 px-4 py-2 text-white disabled:opacity-50">Enregistrer les réinscriptions choisies</button><button disabled={busy||!preview.enrollments.length} onClick={()=>{if(window.confirm('Activer cette année pour toute l’école ? Les opérations nouvelles utiliseront cette année et les historiques seront conservés.'))void act(async()=>{await api.post(`/academic-transition/${yearId}/activate`);window.dispatchEvent(new Event('academic-year-changed'));});}} className="ml-3 rounded border px-4 py-2 disabled:opacity-50">Activer l’année scolaire</button></section>}
  {preview?.year.isCurrent&&<p>Cette année est actuellement active.</p>}
  </div>;
}
