import { useEffect, useState } from 'react';
import api, { studentsApi } from '../services/api';
import { printInvoice, printSchoolDocument, escapeHtml } from '../utils/schoolDocuments';
import { printPaymentReceipt } from '../utils/receipt';
export function ParentPortalPage() {
  const [children,setChildren] = useState<any[]>([]), [student,setStudent] = useState<any>(null), [error,setError]=useState('');
  useEffect(()=>{ studentsApi.getAll().then(setChildren).catch(e=>setError(e.response?.data?.message || 'Chargement impossible.')); },[]);
  const select = async(id:string)=>{setStudent(null);setError('');try{setStudent(await studentsApi.getOne(id));}catch(e:any){setError(e.response?.data?.message || 'Dossier indisponible.');}};
  const download = async(doc:any)=>{try{const response=await api.get(`/parent-portal/students/${student.id}/documents/${doc.id}`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=doc.originalName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError('Téléchargement impossible.');}};
  return <div className="space-y-5 p-4 sm:p-6"><h1 className="text-2xl font-bold">Espace parents</h1><p>Retrouvez les informations scolaires et les documents de vos enfants.</p>{error && <p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="flex flex-wrap gap-3">{children.map(child=><button key={child.id} onClick={()=>void select(child.id)} className="rounded-xl border bg-white p-4 text-left"><strong>{child.firstName} {child.lastName}</strong><p>{child.matricule} — {child.enrollments?.[0]?.classroom?.name}</p></button>)}</div>
    {!children.length && !error && <p>Aucun enfant rattaché à votre adresse e-mail. Contactez le secrétariat pour vérifier le rattachement.</p>}
    {student && <><section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Factures et reçus</h2>{student.invoices?.filter((i:any)=>!i.cancelledAt).map((invoice:any)=><div key={invoice.id} className="space-y-2 border-t py-3"><p>{invoice.title} — Reste à payer : {invoice.balance.toLocaleString('fr-FR')} F CFA</p><button className="rounded border px-3 py-1" onClick={()=>printInvoice({...invoice,student})}>Imprimer la facture</button>{invoice.payments?.filter((p:any)=>!p.cancelledAt).map((payment:any)=><button key={payment.id} className="ml-2 rounded border px-3 py-1" onClick={()=>printPaymentReceipt({payment,invoice:{...invoice,student}})}>Reçu {payment.paymentNumber}</button>)}</div>)}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Présences et absences</h2><p>Présences : {student.attendanceSummary?.present} — Absences : {student.attendanceSummary?.absent} — Retards : {student.attendanceSummary?.late}</p>{student.attendances?.map((row:any)=><p key={row.id}>{new Date(row.date).toLocaleDateString('fr-FR')} — {({PRESENT:'Présent',ABSENT:'Absent',LATE:'En retard',EXCUSED:'Absence justifiée'} as any)[row.status]} — {row.classroom?.name}</p>)}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Notes et bulletins</h2>{student.grades?.map((row:any)=><p key={row.id}>{row.subject?.name} — {row.score}/{row.maxScore} — {row.term}</p>)}{student.reportCards?.map((card:any)=><div key={card.id} className="my-3"><p>{card.classroom?.name} — {card.term} — Moyenne : {card.overallAverage}/20</p><button className="rounded border px-3 py-1" onClick={()=>printSchoolDocument('Bulletin scolaire',`<h3>${escapeHtml(student.firstName)} ${escapeHtml(student.lastName)}</h3><p>${escapeHtml(card.classroom?.name)} — ${escapeHtml(card.term)}</p><p>Moyenne : ${escapeHtml(card.overallAverage)}/20 — Rang : ${escapeHtml(card.rank || '—')}</p><p>${escapeHtml(card.appreciation || '')}</p><p>${escapeHtml(card.teacherRemarks || '')}</p><p>${escapeHtml(card.directorRemarks || '')}</p>`)}>Imprimer le bulletin</button></div>)}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Documents</h2>{student.documents?.map((doc:any)=><button key={doc.id} onClick={()=>void download(doc)} className="mr-3 mt-3 rounded border px-3 py-2">{doc.originalName}</button>)}{!student.documents?.length && <p>Aucun document disponible.</p>}</section></>}
  </div>;
}
