import { t } from '../i18n';
import { SchoolHeader } from '../components/SchoolHeader';
import { programs, money, itemLabels } from '../config/school';
import { printSchoolInformation, schoolNotes } from '../utils/schoolDocuments';
export function SchoolInformationPage() {
  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-8"><SchoolHeader title={t('School information and fees')} year="2026/2027"/><div className="mt-5 flex justify-end"><button onClick={printSchoolInformation} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">{t('Print school information')}</button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{programs.map(p=><article key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-bold text-emerald-950">{t(p.label)}</h3><p className="mt-1 text-sm text-slate-500">{t(p.hours)}{p.minimumAge ? ' · '+t('From six years old'):''}</p><dl className="mt-4 space-y-2 rounded-xl bg-emerald-50 p-3 text-sm"><div className="flex justify-between gap-3"><dt>{t('Initial amount')}</dt><dd className="font-bold">{money(p.registrationFee)}</dd></div><div className="flex justify-between gap-3"><dt>{t('Monthly tuition')}</dt><dd className="font-bold">{money(p.monthlyTuition)}</dd></div></dl>{p.fees.length>1 && <details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold text-emerald-800">{t('Initial amount breakdown')}</summary><dl className="mt-2 space-y-1">{p.fees.map(([label,n])=><div key={label} className="flex justify-between"><dt>{t(label)}</dt><dd>{money(n)}</dd></div>)}</dl></details>}{p.extraSupplies && <p className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-900">{t('Elementary supplies are charged in addition to the initial amount.')} {money(p.extraSupplies)}</p>}<h4 className="mt-4 text-xs font-bold uppercase text-slate-500">{t('Required items')}</h4><ul className="mt-2 space-y-1 text-sm text-slate-600">{p.requiredItems.map(i=><li key={i}>✓ {t(itemLabels[i])}</li>)}</ul></article>)}</div>
    <section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-3"><div><h3 className="font-bold">{t('Transport zone')}</h3><p className="mt-2 text-sm text-slate-600">{t('Zone')} 1 : 10 000 F/{t('month')}<br/>{t('Zone')} 2 : 15 000 F/{t('month')}<br/>{t('Zone')} 3 : 20 000 F/{t('month')}</p></div><div><h3 className="font-bold">{t('Karate')}</h3><p className="mt-2 text-sm text-slate-600">{t('Kimono')} : 6 000 F<br/>2 000 F/{t('month')}</p></div><div><h3 className="font-bold">{t('Evening classes')}</h3><p className="mt-2 text-sm text-slate-600">5 000 F/{t('month')}</p></div></section>
    <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="font-bold text-emerald-950">{t('Important information')}</h3><ul className="mt-3 space-y-2 text-sm text-emerald-900">{schoolNotes().map(note=><li key={note}>• {t(note)}</li>)}<li>• {t('Two diapers are required for children aged two.')}</li></ul></section>
  </div>;
}
