import { getLanguage, t } from '../i18n';
import { ageWarning, effectiveFees, school, programs, programFor, itemLabels, money, transportFees } from '../config/school';
export const escapeHtml = (v:unknown) => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function letterhead(title:string,year=school.year) {
  return `<header><img src="${escapeHtml(new URL(school.logo,window.location.origin).href)}" alt="${escapeHtml(school.name)}"><div><h1>${escapeHtml(school.name)}</h1><p>${escapeHtml(school.address)}</p><p>${escapeHtml(school.phones.join(' / '))}</p><p>${escapeHtml(school.email)} · ${escapeHtml(school.website)}</p></div></header><div class="document-title"><h2>${escapeHtml(title)}</h2><span>${escapeHtml(year)}</span></div>`;
}
export function printSchoolDocument(title:string,body:string,year=school.year) {
  const w=window.open('','_blank','width=900,height=850');if(!w){window.alert(t('Allow pop-ups to print the receipt.'));return;}w.opener=null;
  w.document.write(`<!doctype html><html lang="${getLanguage()}" dir="${getLanguage()==='ar'?'rtl':'ltr'}"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font:12px/1.5 Arial,sans-serif;color:#172c25;margin:0}header{display:flex;align-items:center;gap:20px;border-bottom:2px solid #167341;padding-bottom:12px}header img{width:120px;height:115px;object-fit:contain}header h1{font-size:17px;text-transform:uppercase;margin:0;color:#14532d}header p{font-size:11px;margin:3px 0}.document-title{display:flex;justify-content:space-between;align-items:center;margin:16px 0;background:#ecfdf5;padding:12px}.document-title h2{margin:0;font-size:17px}h3{font-size:13px;color:#14532d;border-bottom:1px solid #cbd5e1;padding-bottom:5px;break-after:avoid}section{margin-bottom:15px;break-inside:avoid}table{width:100%;border-collapse:collapse}th,td{padding:7px;border:1px solid #d1ddd5;text-align:start}th{background:#ecfdf5}ul{padding-inline-start:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.muted{color:#586a60}.signatures{display:flex;justify-content:space-between;margin-top:30px;padding-top:20px;border-top:1px dashed #9ca3af}footer{margin-top:20px;text-align:center;color:#64748b;font-size:10px}.total{font-weight:bold;background:#ecfdf5}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body>${letterhead(title,year)}${body}<footer>${escapeHtml(school.phones.join(' / '))} · ${escapeHtml(school.email)}</footer><script>window.addEventListener('load',()=>{window.focus();window.print()})</script></body></html>`);w.document.close();
}
export function printStudentInformation(student:any) {
  const classroom=student.enrollments?.[0]?.classroom;const program=programFor(classroom);const parent=student.parent || {};const checked=(student.schoolItemsProvided || '').split(',');
  const fields: [string,unknown][] = [['Student name:',`${student.firstName} ${student.lastName}`],['Matricule',student.matricule],['Date of birth',new Date(student.dateOfBirth).toLocaleDateString('fr-SN')],['Assigned class *',classroom?.name],['School programme',t(program.label)],['Hours',t(program.hours)],['Parent / guardian',`${parent.firstName || ''} ${parent.lastName || ''}`],['Phone',parent.phone],['Address',student.address || parent.address],['Emergency contact',student.emergencyContactName],['Emergency telephone',student.emergencyContactPhone]];
  const additional=(transportFees[student.transportZone] || 0)+(student.karate?2000:0)+(student.eveningClasses?5000:0);
  const items=[...program.requiredItems,...(program.id==='PRESCHOOL'?['DIAPERS']:[])];
  const rows=fields.map(([key,value])=>`<tr><th>${escapeHtml(t(key))}</th><td>${escapeHtml(value || '—')}</td></tr>`).join('');
  printSchoolDocument(t('Student information sheet'),`${ageWarning(student.dateOfBirth,classroom)?'<p>'+escapeHtml(t('Below the recommended minimum age; enrolment is permitted.'))+'</p>':''}<p>${escapeHtml(t('Full-day option'))}: ${escapeHtml(t(student.fullDay?'Yes':'No'))} · ${escapeHtml(t('School supplies option'))}: ${escapeHtml(t(student.supplies?'Yes':'No'))}</p><section><table>${rows}</table></section><section><h3>${escapeHtml(t('School options and information'))}</h3><p>${escapeHtml(t('Transport zone'))}: ${student.transportZone || '—'} · ${escapeHtml(t('Karate'))}: ${escapeHtml(t(student.karate?'Yes':'No'))} · ${escapeHtml(t('Evening classes'))}: ${escapeHtml(t(student.eveningClasses?'Yes':'No'))}</p><p>${escapeHtml(t('Monthly tuition'))}: ${money(student.calculatedFees?.monthlyTuition ?? effectiveFees(student,classroom).monthlyTuition)} · ${escapeHtml(t('Additional monthly options'))}: ${money(additional)}</p><p>${escapeHtml(t('Health information and allergies'))}: ${escapeHtml(student.healthNotes || '—')}</p></section><section><h3>${escapeHtml(t('Items already provided'))}</h3><ul>${items.map(item=>`<li>${checked.includes(item)?'☑':'☐'} ${escapeHtml(t(itemLabels[item]))}</li>`).join('')}</ul></section><div class="signatures"><span>${escapeHtml(t('Parent / payer signature'))}</span><span>${escapeHtml(t('School office stamp and signature'))}</span></div>`,student.enrollments?.[0]?.academicYear?.name || school.year);
}
export function printSchoolInformation() {
  const table=programs.map(p=>`<tr><th>${escapeHtml(t(p.label))}<div class="muted">${escapeHtml(t(p.hours))}</div></th><td>${money(p.registrationFee)}</td><td>${money(p.monthlyTuition)}</td></tr>`).join('');
  printSchoolDocument(t('School information and fees'),`<section><table><thead><tr><th>${escapeHtml(t('School programme'))}</th><th>${escapeHtml(t('Initial amount'))}</th><th>${escapeHtml(t('Monthly tuition'))}</th></tr></thead><tbody>${table}</tbody></table></section><section><h3>${escapeHtml(t('Additional options'))}</h3><p>${escapeHtml(t("Transport zone"))}: 1 — 10 000 F ; 2 — 15 000 F ; 3 — 20 000 F / ${escapeHtml(t("month"))}.</p><p>${escapeHtml(t("Karate"))}: 2 000 F / ${escapeHtml(t("month"))} ; ${escapeHtml(t("Kimono"))}: 6 000 F. ${escapeHtml(t("Evening classes"))}: 5 000 F / ${escapeHtml(t("month"))}.</p><p>${escapeHtml(t('Elementary supplies are charged in addition to the initial amount.'))} : 37 500 F.</p></section><section><h3>${escapeHtml(t('Required items'))}</h3>${programs.map(p=>`<p><b>${escapeHtml(t(p.label))}</b> : ${p.requiredItems.map(i=>escapeHtml(t(itemLabels[i]))).join(', ')}${p.minimumAge?' · '+escapeHtml(t('From six years old')):''}</p>`).join('')}</section><section><h3>${escapeHtml(t('Important information'))}</h3><ul>${schoolNotes().map(n=>`<li>${escapeHtml(t(n))}</li>`).join('')}</ul></section>`);
}
export const schoolNotes=()=>['The preschool and elementary initial packages include one monthly tuition payment.','Supplies are available from the school office.','July is part of the school year and is included in enrolment.','June is paid in advance and spread over the other months.','Teaching: 50% Arabic (Islamic and language education), 50% French plus English.'];
export function printInvoice(invoice:any) {
  const student=invoice.student || {};
  const fields:[string,unknown][]=[['Invoice number',invoice.invoiceNumber],['Student name:',`${student.firstName || ''} ${student.lastName || ''}`],['Matricule',student.matricule],['Purpose',invoice.title],['Due date',new Date(invoice.dueDate).toLocaleDateString('fr-SN')],['Created by',invoice.createdByName || '—']];
  printSchoolDocument(t('Invoice'),`<table>${fields.map(([k,v])=>`<tr><th>${escapeHtml(t(k))}</th><td>${escapeHtml(v)}</td></tr>`).join('')}</table><section><h3>${escapeHtml(t('Invoice amount'))}</h3><table><tr><th>${escapeHtml(t('Invoice amount'))}</th><td>${money(invoice.amount)}</td></tr><tr><th>${escapeHtml(t('Total paid'))}</th><td>${money(invoice.paidAmount)}</td></tr><tr class="total"><th>${escapeHtml(t('Balance due'))}</th><td>${money(invoice.balance)}</td></tr></table></section><div class="signatures"><span>${escapeHtml(t('Parent / payer signature'))}</span><span>${escapeHtml(t('School office stamp and signature'))}</span></div>`,invoice.academicYear?.name || school.year);
}
